name: Plugin (Linux)

on:
  push:
    branches: [master]
    paths:
      - .github/workflows/plugin-linux.yml
      - src/SampSharp/**
      - Makefile

    tags:
      - "*"

  pull_request:
    branches: [master]
    paths:
      - .github/workflows/plugin-linux.yml
      - src/SampSharp/**
      - Makefile

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: |
          apt-get update -y -qq
          apt-get upgrade -y gcc-9 g++-9 gcc-9-multilib g++-9-multilib
          gcc-9 --version
          g++-9 --version

      - name: Build plugin
        run: make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: plugin-bin
          path: bin/
